set shiftwidth=4
set tabstop=4
set dictionary=~/.cdict
set textwidth=80

"use :h fo-table for help information about formatoptions
set fo=t

set cindent

"use :h comments for help information
set comments=sl:/*,mb:*,elx:*/

syntax enable
syntax on
colorscheme desert

set tags=./tags
let Tlist_Ctags_Cmd='/usr/bin/ctags'
let Tlist_Use_Right_Window=1 "show taglist window in right window
let Tlist_Exit_OnlyWindow=1 "if taglist window is the only window, exit vim
let Tlist_Show_One_File=0 "only show tags for current file
let Tlist_File_Fold_Auto_Close=1 "only expand tags for current file, tags for other files are folded
let Tlist_Auto_Open=1

autocmd BufRead,BufNewFile *.txt setfiletype text "add new file type
autocmd FileType text setlocal spell spelllang=en_us "config for specific file type
